### ISSUE TITLE
patch problem

### ISSUE THREAD

**Issue by aren13** [Floris497/mac-pixel-clock-patch-V2#1] opened 2016-01-25 11:28 UTC
Hi, 

patch method does not work w/ me.

csrutil is disabled. 

OSX version is 10.11.3 (15D21)

md5 command result is at below

```
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.3 build:15D21

     otool IOKit: e70f3a302a6f87190e6d6fe7609cb4b5
 otool IOKit.bak: e70f3a302a6f87190e6d6fe7609cb4b5
           IOKit: 3cec8ae287ee52a3622082bfc049bb86
       IOKit.bak: a7afb2dd9df1e4c48f12b4b52f7da212

---- ENDING MD5 HASH SUMS -------
```

**Comment by Floris497** [comment] 2016-01-25 12:39
What is the output? it looks like there is still a version of 10.11.2 as a bak file, this may has stopped the script from overwriting the old backup.. if ```md5 -q /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit``` outputs ```a7afb2dd9df1e4c48f12b4b52f7da212``` remove it and try the patch again.

please let me know if that works

**Comment by LETRA** [comment] 2016-01-25 12:54
Hello. Same problem here:

---- BEGINNING MD5 HASH SUMS ---- version: 10.11.3 build:15D21

     otool IOKit: 422c441e207a011b355f712fc0ff7fba
 otool IOKit.bak: e70f3a302a6f87190e6d6fe7609cb4b5
           IOKit: ffc7c67b9facc3bd9a24f39c77d28d0e
       IOKit.bak: a7afb2dd9df1e4c48f12b4b52f7da212

---- ENDING MD5 HASH SUMS -------

**Comment by Floris497** [comment] 2016-01-25 13:09
That is really interesting.. What does ```md5 -q /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit``` and ```md5 -q /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit``` give you? @LETRA it seems like your patch has worked because the code of IOKit has changed. If the otool md5's are different code has changed. The interesting thing is that the IOKit.bak file seems to be the one found in 10.11.2, i'm currently updating my computer to 10.11 so i can see it for myself, can you confirm the patch does not work while the code has changed?

**Comment by Floris497** [comment] 2016-01-25 15:17
There seems to be a little mistake in the script that won't let you use it, i'm fixing it as i speek (typ), quick fix is to run ```$ patch.command patch v6```

**Comment by LETRA** [comment] 2016-01-25 15:32
I can confirm. I tried the update with the earlier version of the script and not worked. And I tried again running the latest version of the script and it has not worked.

**Comment by LETRA** [comment] 2016-01-25 15:39
It does not work with that command. The output is as follows:

Mac-mini-de-LETRA:~ LETRA$ /Users/LETRA/Downloads/IOKit-patcher.command patch v6
An backup file already exists, if you force this patch on an already patched version you will loose the original backup!
This will lead you to reinstall the OS if you loose a working version of IOKit. be carefull
It might be wise to undo the patch before trying to redo it. using: /Users/LETRA/Downloads/IOKit-patcher.command unpatch
Do you want to continue? [Y/n] Y
Mac-mini-de-LETRA:

**Comment by Floris497** [comment] 2016-01-25 16:26
This is unfortunate.. does the old script work? the problem i see is that the version of your IOKit backup is different to mine.. but the code in both patched and unmatched is the same.
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.3 build:15D21

     otool IOKit: 422c441e207a011b355f712fc0ff7fba
 otool IOKit.bak: e70f3a302a6f87190e6d6fe7609cb4b5
           IOKit: 9bf4b606cc64b24c929d662e63730c03
       IOKit.bak: 3cec8ae287ee52a3622082bfc049bb86

---- ENDING MD5 HASH SUMS -------
```

the "IOKit: md5hash" line is different for every person (if it is patched), this due to a unique code signing certificate. but the IOKit.bak file must be the same.. but it is not.. your IOKit.bak has an md5 hash of "a7afb2dd9df1e4c48f12b4b52f7da212" which is the hash of the IOKit of 10.11.2.. it almost looks like an odd update by apple.. my update path was 10.11 -> 10.11.3 but maybe 10.11.2 -> 10.11.3 didn't change the code of IOKit because the code has not changed.. i can only guess they used a different signing certificate..

What version of mac mini do you have? the 2012 model has had some frame buffer updates.. with made this script unusable.. taking back the frame buffer kext from an older version of OS X solved this.. i would recommend reinstalling OS X.. A normal reinstall will take about 40 minutes to an hour.. i'm going to test this on my mini 2011 now.. see what happens.. 

On my mac mini:
```
---- BEGINNING MD5 HASH SUMS ---- version: 10.11.2 build:15C50

     otool IOKit: 422c441e207a011b355f712fc0ff7fba
 otool IOKit.bak: e70f3a302a6f87190e6d6fe7609cb4b5
           IOKit: 5718d75dc7390e3209bb7f8092e7d05b
       IOKit.bak: a7afb2dd9df1e4c48f12b4b52f7da212

---- ENDING MD5 HASH SUMS -------
```

When it is done updating to 10.11.3 i'll see if IOKit was updated or not.. 

very strange condition

**Comment by LETRA** [comment] 2016-01-26 13:06
Hi Floris. I restore OSX from my Time Machine copy. In this moment run 10.11.2 and I doubt update OSX & install the script until you confirm me that's all right.

**Comment by Floris497** [comment] 2016-01-26 14:16
I can confirm it works. I tested it on my 2011 mac mini, what model or mac mini do you have? the 2012 model has been subject to frame buffer changes that made the patch irrelevant.. I hope this is not the case with 10.11.3. What you can see is that your IOKit was correctly patched: ```otool IOKit: 422c441e207a011b355f712fc0ff7fba``` this checksum is the same as mine and at my machine this defiantly worked.. If we would be able to confirm the patch does indeed not work on your system then you must try to update to 10.11.3 run the patch and test if it is working. if it is not working you should copy  either the Apple ```/System/Library/Extensions/AppleIntelFramebufferAzul.kext``` or  ```/System/Library/Extensions/AppleIntelFramebufferCapri.kext``` depending on which one is used for your mac from the Time Machine backup, (it depends on the Integrated graphics you have). Also if you have dedicated graphics This patch works only for integrated graphics. the 'old' one still has support for Nvidia and AMD although i don't usually update them because many people don't want them to be patched. this patch will get it's own Nvidia and AMD patch in the near future.

**Comment by LETRA** [comment] 2016-01-27 01:01
Everything is right now. Thank you very much for your attention Floris.

I use Mac Mini late 2012 i7 2'3 GHz, 16 GB RAM 1600 MHz DDR3, Intel HD Graphics 4000 (1536 MB)

>Información del hardware:
>
>Nombre del modelo:	Mac mini
>Identificador del modelo:	Macmini6,2
>Nombre del procesador:	Intel Core i7
>Velocidad del procesador:	2,3 GHz
>Cantidad de procesadores:	1
>Cantidad total de núcleos:	4
>Caché de nivel 2 (por núcleo):	256 KB
>Caché de nivel 3:	6 MB
>Memoria:	16 GB
>Versión de la ROM de arranque:	MM61.0106.B0A
>Versión SMC (sistema):	2.8f0

>Intel HD Graphics 4000:
>
>Modelo de chipset:	Intel HD Graphics 4000
>Tipo:	GPU
>Bus:	Integrado
>VRAM (dinámica, máx.):	1536 MB
>Fabricante:	Intel (0x8086)
>ID del dispositivo:	0x0166
>ID de la revisión:	0x0009
>
>Pantallas:
>
>LG ULTRAWIDE:
>Resolución:	2560 x 1080 @ 60 Hz
>Profundidad de píxel:	Color de 32 bits (ARGB8888)
>Pantalla principal:	Sí
>Duplicado:	Desactivado
>En línea:	Sí
>Rotación:	Compatible
>Televisor:	Sí
>
>LG ULTRAWIDE:
>Resolución:	2560 x 1080 @ 60 Hz
>Profundidad de píxel:	Color de 32 bits (ARGB8888)
>Duplicado:	Desactivado
>En línea:	Sí
>Rotación:	Compatible
>Televisor:	Sí

**Comment by LETRA** [comment] 2016-01-27 01:04
The right output:

>Last login: Wed Jan 27 01:33:57 on console
>Mac-mini-de-LETRA:~ LETRA$ chmod +x /Users/LETRA/Downloads/IOKit-patcher.command
>Mac-mini-de-LETRA:~ LETRA$ /Users/LETRA/Downloads/IOKit-patcher.command(otool) Detected >unpatched IOKit on OS X 10.11.2 and 10.11.3.
>Patching IOKit with patch version 6
>Password:
>Re-singing IOKit
>/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit: replacing existing signature
>Closing..
>Mac-mini-de-LETRA:~ LETRA$ /Users/LETRA/Downloads/IOKit-patcher.command test
>(otool) Detected patched IOKit on OS X 10.11.2 and 10.11.3.
>Mac-mini-de-LETRA:~ LETRA$

Thank you !!

**Comment by Floris497** [comment] 2016-01-27 09:09
Great :) I'm happy it works now!

If @aren13 can confirm his version works too I can close the issue.

**Comment by Devolv** [comment] 2016-01-29 16:24
Doesn't work for me either...

Here's my md5 results.

`---- BEGINNING MD5 HASH SUMS ---- version: 10.11.3 build:15D21

     otool IOKit: e70f3a302a6f87190e6d6fe7609cb4b5
 otool IOKit.bak: 6999a527ba1a10c38a76295981026df1
           IOKit: 3cec8ae287ee52a3622082bfc049bb86
       IOKit.bak: cf5811f915406b59a5e382e11a52135a

---- ENDING MD5 HASH SUMS -------`

**Comment by Floris497** [comment] 2016-01-29 17:02
Yep that looks totally fine :D As long as nothing weird has happend and ```tool IOKit``` and ```tool IOKit.bak``` are different the patch has been successful :)

**Closed** 2016-02-06 12:01 UTC
